### ISSUE TITLE
Excellent explaination just two things to clarify

### ISSUE THREAD

**Issue by zilexa** [ausbin/nsdo#1]
Only two things are unclear to me:
1)
> I named my script /usr/local/bin/vpn-ns

I assume you mean the second script below this line, which is your version of Sebastian's script. Correct?
 

2)
> so here's the relevant snippet from my openvpn configuration file:

It is unclear to me if this snippet should be copied to a new .conf file or if I should add it to my VPN provider's .conf file (which you call foo.conf in your explanation)?
 
All the rest is pretty clear and very well explained!

**Comment by ausbin** [comment]
Thanks for the feedback!

I answered these questions in our email thread, but for the benefit of future visitors:

> I assume you mean the second script below this line, which is your version of Sebastian's script. Correct?

Yes.

> It is unclear to me if this snippet should be copied to a new .conf file or if I should add it to my VPN provider's .conf file (which you call foo.conf in your explanation)?

Append it to your provider's openvpn config file.

If you think the guide needs work, would you mind creating a PR? I'm not sure what improvements you have in mind. (Just don't forget to wrap lines at 72 columns — it's a sad obsession of mine)

**Comment by ausbin** [comment]
I moved the article to my blog, so I'm going to close this issue. Still, you're more than welcome to create a pull request there at https://github.com/ausbin/blog.

Thanks again for the feedback.
