### ISSUE TITLE
How to install on OSMC?

### ISSUE THREAD

**Issue by zilexa** [ausbin/nsdo#4]
Hi Ausbin, how should one install this on OSMC? It is based on Debian 8.9. 
It is a distribution for the Raspberry Pi devices, but since it runs on Debian I let the Raspberry run Flexget and Transmission as well as SyncThing. I want to run the first two applications via VPN while leaving the rest untouched.

**Comment by ausbin** [comment]
Hey,

Try doing

    make
    sudo make install

in this repo and then following https://austinjadams.com/blog/running-select-applications-through-openvpn/. Let me know how it works out

**Comment by zilexa** [comment]
Sorry for the delay. But I am a bit of a noob when it comes to linux. 
The command "make" does not exist via bash. I suppose you mean I should install Github on my Raspberry first?
Otherwise I am not sure how to add your repo. I know for example how to add a repo to my device, this is how I added the repo of Raspotify:
```
# pgp key
curl -sSL https://dtcooper.github.io/raspotify/key.asc | sudo apt-key add -v -
# add repo
echo 'deb https://dtcooper.github.io/raspotify jessie main' | sudo tee /etc/apt/sources.list.d/raspotify.list
```
after that I could just do `apt-get install raspotify`

I guess I am looking for similar instructions..

**Comment by zilexa** [comment]
I figured it out: I installed make first, then downloaded your files and then tried make install, unfortunately it failed.
``` 
~$ wget https://github.com/ausbin/nsdo/archive/master.zip
--2017-09-15 17:00:31--  https://github.com/ausbin/nsdo/archive/master.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/ausbin/nsdo/zip/master [following]
--2017-09-15 17:00:31--  https://codeload.github.com/ausbin/nsdo/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7566 (7.4K) [application/zip]
Saving to: ‘master.zip’

master.zip          100%[=====================>]   7.39K  --.-KB/s   in 0.002s

2017-09-15 17:00:32 (4.16 MB/s) - ‘master.zip’ saved [7566/7566]
```
```
~$ unzip -d ~/ master.zip
Archive:  master.zip
   creating: nsdo-master/
  inflating: nsdo-master/.gitignore
  inflating: nsdo-master/LICENSE
  inflating: nsdo-master/Makefile
  inflating: nsdo-master/README.md
   creating: nsdo-master/bash_completion/
  inflating: nsdo-master/bash_completion/nsdo
  inflating: nsdo-master/nsdo.1
  inflating: nsdo-master/nsdo.c
  inflating: nsdo-master/openvpn-example.md
  inflating: nsdo-master/readme.head
```
````
:~/nsdo-master$ make
cc -Wall -O2 -pedantic    nsdo.c   -o nsdo
make: cc: Command not found
<builtin>: recipe for target 'nsdo' failed
make: *** [nsdo] Error 127
```
```
osmc@ChilleTV:~/nsdo-master$ make install
cc -Wall -O2 -pedantic    nsdo.c   -o nsdo
make: cc: Command not found
<builtin>: recipe for target 'nsdo' failed
make: *** [nsdo] Error 127
```

**Comment by ausbin** [comment]
Install the build-essential package. You need a C compiler (aka cc)

**Comment by zilexa** [comment]
That did the trick! It is installed now and I will follow your blog to set it up. I intend to use it only for Flexget and Transmission. Flexget is python based and calls other tools to do the work, like subliminal and site scrapers. I hope if Flexget service is started via nsdo, any applications it will call, will run via the namespace. Not sure how to test this but I will try following your blog first. Thanks!

**Comment by ausbin** [comment]
i'm gonna close this, but lmk if this is still giving you issues
